name: editguard_coco_finetune
model: MIMO-VRN-h
scale: 4

gpu_ids: [0]
gop: 1
num_image: 1
nf: 12
is_train: True
distortion: none
addnoise: False
addjpeg: False
addpossion: False
sdinpaint: False
controlnetinpaint: False
sdxl: False
repaint: False
hide: True
bithide: False
degrade_shuffle: False
prompt: True
prompt_len: 3
message_length: 64
losstype: mse
mode: image

use_tb_logger: true
dist: False

# ----------------- Datasets -----------------
datasets:
  TD:
    num_image: 1
    name: COCO2017_test
    mode: test
    dataroot_GT: /mnt/ssd/BG/EditGuard/EditGuard/COCO2017/sample10
    txt_path: /mnt/ssd/BG/EditGuard/EditGuard/COCO2017/sample10.txt

    interval_list: [1]
    random_reverse: false
    border_mode: false
    N_frames: 1

    use_shuffle: true
    n_workers: 8
    batch_size: 1
    GT_size: 256
    color: RGB
    use_flip: true
    use_rot: true

# ----------------- Network -----------------
network_G:
  which_model_G: IBSN          # train이랑 맞춤
  subnet_type: DBNet
  in_nc: 12
  out_nc: 12
  block_num: [6, 6]
  scale: 2
  init: xavier_group
  block_num_rbm: 8
  block_num_trans: 4

# ----------------- Path -----------------
path:
  pretrain_model_G: /mnt/ssd/BG/EditGuard/EditGuard/experiments/editguard_coco_finetune_archived_251118-052238/models/5000_G.pth  # baseline ckpt
  models: /mnt/ssd/BG/EditGuard/EditGuard/experiments/editguard_coco_eval/models
  experiments_root: /mnt/ssd/BG/EditGuard/EditGuard/experiments/editguard_coco_eval
  logs: /mnt/ssd/BG/EditGuard/EditGuard/experiments/editguard_coco_eval/logs
  strict_load: false
  resume_state: ~

# ----------------- Train (형식 맞추기용; test.py에서는 거의 안 씀) -----------------
train:
  lr_G: '2e-4'
  beta1: 0.9
  beta2: 0.999
  val_freq: 5000
  save_freq: 5000
  niter: 200000
  lr_scheme: MultiStepLR
  lr_steps: [50000, 100000, 150000]
  lr_gamma: 0.5
  weight_decay_G: 0
  N_frames: 1
  warmup_iter: 0
  pixel_criterion_forw: l2
  lambda_fit_forw: 1.0
  lambda_rec_back: 1.0
  lambda_crossover: 1.0
  lambda_bit: 1.0

loss:
  pixel_weight: 1.0
  vgg_weight: 1.0
  lpips_weight: 1.0

logger:
  display_freq: 100
  save_checkpoint_freq: 5000
  print_freq: 100
